INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '쌀');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '잡곡/혼합곡');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '농협양곡');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '과일');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '견과류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '냉동/건과일');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '뿌리채소');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '열매채소');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '김치');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '반찬');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '소고기');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '돼지고기');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '닭고기/계란');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '기타축산물');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '수산물');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '축산가공식품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '즉석밥');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '라면');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '과자/간식');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '빙과류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '통조림/캔');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '조미료/양념');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '장류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', '노트북');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', 'PC');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', '노트북용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '모니터');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '모니터용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '프린터');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '프린터용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '스캐너');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC주변용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC부품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC입력장치');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC영상/음향장치');

INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마틴', '좋은 쌀', 30000, 3000, 0, 1);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마틴', '좋은 잡곡', 25000, 3000, 0, 2);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('농협', '좋은 농협 쌀', 25000, 3000, 0, 3);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마틴', '사과', 2000, 0, 0, 4);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('좋은견과류', '호두', 3000, 0, 0, 5);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('좋은견과류', '건포도', 2000, 0, 0, 6);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('뿌리왕', '좋은 무', 4000, 0, 0, 7);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('열매왕', '열매다', 5000, 2000, 0, 8);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('삐비고', '배추김치', 12000, 2000, 0, 9);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('수미네', '장조림', 6000, 2500, 0, 10);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('횡성', '한우 안창살', 22000, 0, 0, 11);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('돼지킹', '돼지고기 삼겹살', 12000, 0, 0, 12);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('꼬끼오', '닭 한마리', 5000, 0, 0, 13);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('기타라고', '뭐있지', 1000, 3000, 0, 14);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('수산수산', '갈치', 8000, 2000, 0, 15);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('가공육고기', '불고기', 12000, 0, 0, 16);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('해햇', '햇반', 1000, 3000, 0, 17);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('삼양', '삼양라면', 4500, 2500, 0, 18);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('지금내가', '해바라기씨', 12000, 0, 0, 19);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('월슈', '월드슈퍼콘', 2000, 5000, 0, 20);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('참치다', '고추참치', 3000, 5000, 0, 21);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마법의소스', '굴소스', 5000, 3000, 0, 22);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마법의간장', '진간장', 7000, 2000, 0, 23);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('사과마을', '매그북', 2000000, 0, 0, 24);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('사과마을', '나는맥', 3000000, 0, 0, 25);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('사과마을', '트랙패드', 200000, 0, 0, 26);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('별세개', '24인치 모니터', 120000, 0, 0, 27);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('기타등등', '모니터 클리너', 12000, 3000, 0, 28);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('별세개', '잉크젯 프린터', 50000, 0, 0, 29);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('별세개', '잉크 토너', 20000, 5000, 0, 30);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('별세개', '스캐애앤', 40000, 0, 0, 31);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('사과농장', '감성의마우스', 60000, 0, 0, 32);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('앤비디암드', '좋은그래픽', 200000, 0, 0, 33);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마틴', '블루투스 키보드', 30000, 0, 0, 34);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('마틴', '탁상용 마이크', 20000, 5000, 0, 35);
INSERT INTO PRODUCT (BRAND_NAME, PRODUCT_NAME, PRICE, SHIPPING_FEE, TYPE, CATEGORY_ID)
VALUES ('이벤트', '헤드셋', 10000, 0, 1, 35);