INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '쌀');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '잡곡/혼합곡');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '농협양곡');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '과일');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '견과류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '냉동/건과일');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '뿌리채소');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '열매채소');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '김치');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '반찬');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '소고기');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '돼지고기');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '닭고기/계란');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '기타축산물');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '수산물');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '축산가공식품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '즉석밥');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '라면');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '과자/간식');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '빙과류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '통조림/캔');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '조미료/양념');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '가공식품', '장류');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', '노트북');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', 'PC');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '노트북/PC', '노트북용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '모니터');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '모니터용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '프린터');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '프린터용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', '모니터/프린터', '스캐너');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC주변용품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC부품');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC입력장치');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('컴퓨터', 'PC주변기기', 'PC영상/음향장치');

