INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '쌀');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '잡곡/혼합곡');
INSERT INTO CATEGORY (TOP_CATEGORY, SUB_CATEGORY, LOWEST_CATEGORY)
VALUES ('식품', '신선식품', '농협양곡');
